
/*#389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"*/


#include <vector>
#include <iostream>
using namespace std;

class Solution {
public:
   
      char findTheDifference(string s, string t)
     {
        unordered_map<char, int>mp;
        
        for(char &ch : s)
        {
            mp[ch]++;

        }
        for(char &ch : t)
        {
            mp[ch]--;

            if(mp[ch]<0)
            {
                return ch;
            }
        }

            return 'x';
        
     }  

      char findTheDifference(string s, string t)
     {
         int sum_s = 0;

         for (char &ch : s)
         {
             sum_s += ch;
         }
         int sum_t = 0;

         for (char &ch : t)
         {
             sum_t += ch;
         }

         return char(sum_t - sum_s);
     }  

      char findTheDifference(string s, string t)
     {
         int sum = 0;

         for (char &ch : s)
         {
             sum += ch;
         }
         int sum_t = 0;

         for (char &ch : t)
         {
             sum -= ch;
         }

         return char(sum);
     }  


      char findTheDifference(string s, string t)
     {
        int XOR =0;
        for(char &ch : s)
        {
            XOR ^= ch;
        }
        for(char &ch : t)
        {
           XOR ^= ch;
            
        }

        return char(XOR);
        
    
     }               
             
    
};